import { Grid } from "@mui/material";
import Carousel from "../../components/Carousel";
import CustomAccordion from "../../components/Accordion";
import BlockQuote from "../../components/BlockQuote";

function Reticle() {
  // Define topics here if they need dynamic rendering or pass them as props
  const topics = [
    {
      heading: "Types of Reticles",
      sections: [
        {
          question: "What is a stadiametric reticle?",
          answer: [
            "A stadiametric reticle (choke sight or stadia reticle) is a type of reticle that is used to estimate the range of a target based on its size.",
            "Vertical and horizontal lines are used to measure the height and width of a target in mils or MOA.",
          ],
        },
        {
          question: "What is thermal optics?",
          answer: [
            "Thermal optics display an image based on the middle and far length infrared spectrum.",
            <span>
              <strong>
                Thermal optics CANNOT see infrared equipment, but they can see
                the heat generated by the equipment!
              </strong>
            </span>,
          ],
        },
        {
          question: "What is night vision?",
          answer: [
            "Night vision devices are considered image intensifiers, they amplify ambient light, and are used to see in low light conditions.",
            "They detect the near infrared spectrum and cannot see heat generated by equipment.",
          ],
        },
      ],
    },
    {
      heading: "Advantages and Disadvantages of Reticles",
      sections: [
        {
          question: "When is infrared imaging not effective?",
          answer: [
            "Water and glass act as a barrier that reflects infrared light and can give false readings.",
            "Rain absorbs infrared light and can make it difficult to see through.",
          ],
        },
        {
          question: "When is infrared imaging effective?",
          answer: [
            "Smoke does not obfuscate unless it is hot and dense enough to block the infrared light or if the target is on top of the smoke-source.",
            "Dust does not interfere either unless the dust is the same temperature as the target or if the debris is dense.",
          ],
        },
      ],
    },
  ];

  return (
    <>
      <Grid
        container
        id="page"
        rowSpacing={1}
        columnSpacing={{ xs: 1, sm: 2, md: 3 }}
      >
        <Grid
          item
          xs={12}
          sm={9}
          md={9}
          lg={10}
          container
          direction="column"
          className="right-container"
        >
          <Grid item className="item-spacing">
            <BlockQuote
              header="Reticle"
              content={[
                "The reticle is the aiming point of the weapon system and is often measured in MILS or MOA.",
              ]}
              source={["- TC 3-22.9"]}
            />
          </Grid>
          <Grid item className="image">
            <Carousel
              image="https://www.placehold.it/550x350"
              alt="Placehold.it image"
            />
          </Grid>
          {topics.map((topic, index) => (
            <Grid item key={index} className="topic-container">
              <CustomAccordion topics={[topic]} />
            </Grid>
          ))}
        </Grid>
      </Grid>
    </>
  );
}

export default Reticle;
